import { z } from 'zod'

export const RegisterCanvasUserSchema = z.object({
  canvas_user_id: z.string().min(1),
  institution_url: z.string().url(),
  email: z.string().email().nullish(),
  display_name: z.string().nullish(),
})

export type RegisterCanvasUserInput = z.infer<typeof RegisterCanvasUserSchema>

// Used by POST /api/auth/extension — no JWT required, this IS the auth step.
// Merges canvas user registration so auth + canvas_users upsert are atomic.
export const ExtensionAuthSchema = z.object({
  canvas_user_id: z.string().min(1),
  institution_url: z.string().url(),
  display_name: z.string().nullish(),
  email: z.string().email().nullish(),
})

export type ExtensionAuthInput = z.infer<typeof ExtensionAuthSchema>

// Used by POST /api/auth/canvas-token — requires extension JWT.
// Stores the Canvas personal access token generated by the extension.
export const StoreCanvasTokenSchema = z.object({
  canvas_token: z.string().min(1),
})

export type StoreCanvasTokenInput = z.infer<typeof StoreCanvasTokenSchema>

// Used by POST /api/auth/link-canvas — requires JWT of the web app user.
// Associates the authenticated web user with the given canvas identity.
export const LinkCanvasSchema = z.object({
  canvas_user_id: z.string().min(1),
  institution_url: z.string().url(),
})

export type LinkCanvasInput = z.infer<typeof LinkCanvasSchema>
