import { NextRequest, NextResponse } from 'next/server'
import { verifyJwt } from '../../../../src/lib/verifyJwt'
import { StoreCanvasTokenSchema } from '../../../../src/schemas/auth'
import { storeCanvasToken } from '../../../../src/services/authService'

export async function OPTIONS() {
  return new NextResponse(null, { status: 204 })
}

// POST /api/auth/canvas-token — requires Bearer JWT (extension user)
// Stores the Canvas personal access token generated by the extension so the
// backend can fetch live Canvas data on behalf of the user from the web app.
export async function POST(req: NextRequest) {
  try {
    const { userId } = await verifyJwt(req.headers.get('Authorization'))
    const body: unknown = await req.json()
    const input = StoreCanvasTokenSchema.parse(body)
    await storeCanvasToken(userId, input)
    return NextResponse.json({ ok: true }, { status: 200 })
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unknown error'
    const status = message.includes('JWT') || message.includes('Authorization') ? 401 : 400
    return NextResponse.json({ error: message }, { status })
  }
}
