-- Seed shop items (100+ items for course requirements)
-- Run this after schema.sql

INSERT INTO shop_items (name, description, cost, image_url, active) VALUES
-- Hats (20 items)
('Party Hat', 'A colorful cone hat for celebrations', 50, NULL, true),
('Wizard Hat', 'A mystical purple wizard hat', 120, NULL, true),
('Crown', 'A golden crown fit for royalty', 500, NULL, true),
('Baseball Cap', 'A casual red baseball cap', 30, NULL, true),
('Top Hat', 'A classy black top hat', 150, NULL, true),
('Beanie', 'A cozy winter beanie', 40, NULL, true),
('Cowboy Hat', 'Yeehaw! A brown cowboy hat', 80, NULL, true),
('Chef Hat', 'A tall white chef toque', 70, NULL, true),
('Pirate Hat', 'Arrr! A swashbuckling pirate hat', 100, NULL, true),
('Santa Hat', 'A festive red and white hat', 60, NULL, true),
('Graduation Cap', 'For the scholarly pet', 200, NULL, true),
('Viking Helmet', 'A horned warrior helmet', 180, NULL, true),
('Flower Crown', 'A delicate crown of flowers', 45, NULL, true),
('Propeller Hat', 'A silly spinning propeller hat', 35, NULL, true),
('Beret', 'An artistic French beret', 55, NULL, true),
('Sombrero', 'A festive Mexican sombrero', 90, NULL, true),
('Fedora', 'A stylish detective fedora', 75, NULL, true),
('Halo', 'A glowing angelic halo', 300, NULL, true),
('Devil Horns', 'Mischievous little horns', 65, NULL, true),
('Bunny Ears', 'Cute floppy bunny ears', 50, NULL, true),

-- Accessories (20 items)
('Bow Tie', 'A dapper red bow tie', 25, NULL, true),
('Necktie', 'A professional blue necktie', 30, NULL, true),
('Scarf', 'A warm striped scarf', 35, NULL, true),
('Sunglasses', 'Cool black sunglasses', 60, NULL, true),
('Monocle', 'A distinguished monocle', 100, NULL, true),
('Necklace', 'A sparkling gem necklace', 150, NULL, true),
('Bandana', 'A red western bandana', 20, NULL, true),
('Headphones', 'Oversized DJ headphones', 80, NULL, true),
('Glasses', 'Nerdy round glasses', 40, NULL, true),
('Eye Patch', 'A pirate eye patch', 25, NULL, true),
('Mustache', 'A curly fake mustache', 15, NULL, true),
('Beard', 'A magnificent fake beard', 20, NULL, true),
('Wings', 'Sparkly fairy wings', 200, NULL, true),
('Cape', 'A superhero cape', 120, NULL, true),
('Backpack', 'A tiny adventurer backpack', 70, NULL, true),
('Medal', 'A shiny gold medal', 90, NULL, true),
('Badge', 'A sheriff star badge', 45, NULL, true),
('Earrings', 'Dangly star earrings', 55, NULL, true),
('Watch', 'A fancy wristwatch', 85, NULL, true),
('Bracelet', 'A friendship bracelet', 30, NULL, true),

-- Backgrounds (20 items)
('Sunny Meadow', 'A peaceful grassy meadow', 100, NULL, true),
('Beach Sunset', 'A beautiful ocean sunset', 120, NULL, true),
('Space Galaxy', 'A cosmic starry background', 200, NULL, true),
('Cozy Room', 'A warm indoor room', 80, NULL, true),
('Forest', 'A magical enchanted forest', 150, NULL, true),
('City Skyline', 'An urban nighttime skyline', 130, NULL, true),
('Underwater', 'A deep sea ocean scene', 140, NULL, true),
('Mountain Peak', 'A snowy mountain summit', 110, NULL, true),
('Candy Land', 'A sweet candy wonderland', 180, NULL, true),
('Haunted House', 'A spooky haunted mansion', 160, NULL, true),
('Rainbow Sky', 'A colorful rainbow backdrop', 90, NULL, true),
('Winter Wonderland', 'A snowy winter scene', 100, NULL, true),
('Cherry Blossoms', 'Pink sakura trees', 140, NULL, true),
('Desert Oasis', 'A sandy desert with palm trees', 95, NULL, true),
('Volcano', 'A dramatic volcanic landscape', 170, NULL, true),
('Cloud Kingdom', 'Fluffy clouds in the sky', 130, NULL, true),
('Jungle', 'A lush tropical jungle', 125, NULL, true),
('Arctic Ice', 'A frozen arctic landscape', 115, NULL, true),
('Pixel Grid', 'A retro pixel art grid', 50, NULL, true),
('Gradient Wave', 'A smooth color gradient', 60, NULL, true),

-- Colors/Skins (20 items)
('Golden Glow', 'A shimmering gold skin', 400, NULL, true),
('Rainbow Sparkle', 'A multicolor rainbow skin', 350, NULL, true),
('Midnight Blue', 'A deep blue color scheme', 80, NULL, true),
('Sunset Orange', 'A warm orange gradient', 80, NULL, true),
('Forest Green', 'A natural green tint', 80, NULL, true),
('Cotton Candy', 'Pink and blue pastel', 100, NULL, true),
('Lava Red', 'A fiery red hot skin', 120, NULL, true),
('Ice Crystal', 'A cool icy blue skin', 120, NULL, true),
('Shadow Black', 'A mysterious dark skin', 150, NULL, true),
('Snow White', 'A pure white skin', 100, NULL, true),
('Bubblegum Pink', 'A bright pink color', 70, NULL, true),
('Lavender Dream', 'A soft purple hue', 75, NULL, true),
('Mint Fresh', 'A cool mint green', 75, NULL, true),
('Coral Reef', 'A peachy coral color', 85, NULL, true),
('Storm Gray', 'A sleek gray tone', 65, NULL, true),
('Neon Glow', 'A bright neon outline', 200, NULL, true),
('Holographic', 'A shifting holographic effect', 500, NULL, true),
('Camo Pattern', 'A camouflage pattern', 90, NULL, true),
('Polka Dots', 'A cute dotted pattern', 60, NULL, true),
('Stripes', 'Classic striped pattern', 55, NULL, true),

-- Effects/Animations (15 items)
('Sparkle Trail', 'Leave a trail of sparkles', 250, NULL, true),
('Heart Bubbles', 'Floating heart particles', 180, NULL, true),
('Star Burst', 'Twinkling star effects', 200, NULL, true),
('Fire Aura', 'A flaming aura effect', 300, NULL, true),
('Ice Crystals', 'Floating ice particles', 280, NULL, true),
('Music Notes', 'Dancing music notes', 150, NULL, true),
('Lightning', 'Electric sparks effect', 320, NULL, true),
('Confetti', 'Falling confetti celebration', 120, NULL, true),
('Snowflakes', 'Gentle falling snow', 140, NULL, true),
('Leaves', 'Autumn falling leaves', 130, NULL, true),
('Bubbles', 'Floating soap bubbles', 100, NULL, true),
('Fireflies', 'Glowing firefly lights', 160, NULL, true),
('Rainbow Trail', 'A colorful rainbow trail', 220, NULL, true),
('Ghost Wisps', 'Spooky floating wisps', 170, NULL, true),
('Pixel Dust', 'Retro pixel particle effect', 190, NULL, true),

-- Special/Rare (10 items)
('Legendary Sword', 'An epic glowing sword', 1000, NULL, true),
('Dragon Pet', 'A tiny dragon companion', 2000, NULL, true),
('UFO', 'A hovering alien spacecraft', 1500, NULL, true),
('Time Machine', 'A miniature time machine', 1800, NULL, true),
('Magic Wand', 'A powerful wizard wand', 800, NULL, true),
('Treasure Chest', 'A golden treasure chest', 600, NULL, true),
('Robot Buddy', 'A mechanical robot friend', 1200, NULL, true),
('Phoenix Feather', 'A rare phoenix feather', 900, NULL, true),
('Crystal Ball', 'A mystical crystal ball', 700, NULL, true),
('Infinity Gem', 'An all-powerful gem', 5000, NULL, true);
