-- v3: Add canvas_token column to canvas_users
-- Run this on an existing Supabase project that already has the schema.sql base applied.
-- For a fresh project, schema.sql already includes this column.

alter table canvas_users
  add column if not exists canvas_token text;

comment on column canvas_users.canvas_token is
  'Personal access token generated by the extension via the user''s Canvas session. '
  'Used by the backend to fetch live Canvas data for the web app. '
  'Stored plaintext — encrypt with pgp_sym_encrypt for production use.';
