import { createHmac } from 'crypto'
import { getSupabaseAdmin } from '../lib/supabaseAdmin'
import type { RegisterCanvasUserInput, ExtensionAuthInput, LinkCanvasInput, StoreCanvasTokenInput } from '../schemas/auth'

// Creates or signs in the Supabase Auth user for a given Canvas identity, then
// upserts their canvas_users row atomically. No JWT required — this IS the auth step.
// The password is a keyed HMAC so external actors cannot forge credentials without
// knowing EXTENSION_SECRET.
export async function signInExtensionUser(input: ExtensionAuthInput) {
  const secret = process.env.EXTENSION_SECRET!
  const email = `canvas_${input.canvas_user_id}@canvaspet.internal`
  const password = createHmac('sha256', secret)
    .update(`${input.canvas_user_id}:${input.institution_url}`)
    .digest('hex')

  // Happy path: returning user — sign in and update canvas_users
  const { data: signInData, error: signInError } =
    await getSupabaseAdmin().auth.signInWithPassword({ email, password })

  if (!signInError && signInData.session) {
    await upsertCanvasUser(signInData.session.user.id, input)
    return signInData.session
  }

  // New user — create auth account, upsert canvas_users, then sign in
  const { data: created, error: createError } =
    await getSupabaseAdmin().auth.admin.createUser({ email, password, email_confirm: true })
  if (createError || !created.user) {
    throw new Error(`Failed to create extension user: ${createError?.message}`)
  }
  await upsertCanvasUser(created.user.id, input)

  const { data, error } = await getSupabaseAdmin().auth.signInWithPassword({ email, password })
  if (error || !data.session) throw new Error(`Extension auth failed: ${error?.message}`)
  return data.session
}

// Upserts a canvas_users row keyed on the Supabase Auth user ID.
// Called atomically inside signInExtensionUser (new users) and by POST /api/auth
// (subsequent sessions / web app token flow).
export async function upsertCanvasUser(
  supabaseAuthUserId: string,
  input: RegisterCanvasUserInput,
): Promise<void> {
  const { error } = await getSupabaseAdmin()
    .from('canvas_users')
    .upsert(
      {
        id: supabaseAuthUserId,
        canvas_user_id: input.canvas_user_id,
        institution_url: input.institution_url,
        email: input.email ?? null,
        display_name: input.display_name ?? null,
        updated_at: new Date().toISOString(),
      },
      { onConflict: 'id' },
    )
  if (error) throw new Error(`Failed to upsert canvas user: ${error.message}`)
}

// Links a web app user to a canvas_users row by canvas_user_id + institution_url.
// Called by POST /api/auth/link-canvas after the web user signs in.
export async function linkCanvasUser(
  webSupabaseUserId: string,
  webDisplayName: string | null,
  webEmail: string | null,
  input: LinkCanvasInput,
): Promise<void> {
  const { error } = await getSupabaseAdmin()
    .from('canvas_users')
    .update({
      web_user_id: webSupabaseUserId,
      web_display_name: webDisplayName,
      web_email: webEmail,
      updated_at: new Date().toISOString(),
    })
    .eq('canvas_user_id', input.canvas_user_id)
    .eq('institution_url', input.institution_url)
  if (error) throw new Error(`Failed to link canvas user: ${error.message}`)
}

// Stores the Canvas personal access token for the given Supabase Auth user.
// The token is generated by the extension using the user's Canvas session and
// is used by the backend to fetch live Canvas data for the web app.
export async function storeCanvasToken(
  supabaseAuthUserId: string,
  input: StoreCanvasTokenInput,
): Promise<void> {
  const { error } = await getSupabaseAdmin()
    .from('canvas_users')
    .update({ canvas_token: input.canvas_token, updated_at: new Date().toISOString() })
    .eq('id', supabaseAuthUserId)
  if (error) throw new Error(`Failed to store Canvas token: ${error.message}`)
}

// Returns the Canvas user ID stored for a given Supabase Auth user.
// All write routes call this so the server resolves the Canvas identity from
// the JWT — the client never gets to claim a canvas_user_id directly.
export async function getCanvasUserIdForAuthUser(
  supabaseAuthUserId: string,
): Promise<string> {
  const { data, error } = await getSupabaseAdmin()
    .from('canvas_users')
    .select('canvas_user_id')
    .eq('id', supabaseAuthUserId)
    .single()
  if (error || !data) throw new Error('Canvas user not found — call POST /api/auth first')
  return data.canvas_user_id as string
}
